services:
  app:
    image: ghcr.io/holgerengels/tix:latest
    ports:
      - "3000:3000"
    volumes:
      - ./config:/config
    extra_hosts:
      - "host.docker.internal:host-gateway"
      # - "myserver.local:192.168.1.50" # Example: Map hostname to IP
    depends_on:
      - mongo
    restart: always

  mongo:
    image: mongo:latest
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    restart: always

volumes:
  mongo-data:
