services:
  app:
    image: ghcr.io/holgerengels/tix:latest
    ports:
      - "3000:3000"
    volumes:
      - ./config:/config
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    extra_hosts:
      - "host.docker.internal:host-gateway"
      - "vu.webuntis.com:213.208.138.156"
      - "vu.webuntis.com:213.208.138.157"
      - "vu.webuntis.com:213.208.138.155"
      - "vu.webuntis.com:213.208.138.154"
      - "mail.valckenburgschule.de:148.251.5.116"
    environment:
      - http_proxy
      - https_proxy
      - no_proxy
      - HTTP_PROXY
      - HTTPS_PROXY
      - NO_PROXY
    depends_on:
      - mongo
    restart: always

  mongo:
    image: mongo:latest
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    restart: always

volumes:
  mongo-data:
