import { precacheAndRoute } from 'workbox-precaching'

// Precache all assets generated by Vite
precacheAndRoute(self.__WB_MANIFEST || [])

self.addEventListener('message', (event) => {
    if (event.data && event.data.type === 'SKIP_WAITING') {
        self.skipWaiting()
    }
})

self.addEventListener('push', function (event) {
    if (event.data) {
        try {
            const data = event.data.json()
            const title = data.title || 'TIX Benachrichtigung'
            const options = {
                body: data.body,
                icon: '/pwa-192x192.png',
                badge: '/masked-icon.png',
                data: {
                    url: data.url || '/'
                }
            }
            event.waitUntil(self.registration.showNotification(title, options))
        } catch (e) {
            console.error('Error parsing push data:', e)
            event.waitUntil(
                self.registration.showNotification('TIX', {
                    body: event.data.text(),
                    icon: '/pwa-192x192.png'
                })
            )
        }
    }
})

self.addEventListener('notificationclick', function (event) {
    event.notification.close()

    const urlToOpen = new URL(event.notification.data.url, self.location.origin).href

    event.waitUntil(
        clients.matchAll({ type: 'window', includeUncontrolled: true }).then((windowClients) => {
            // Check if there is already a window/tab open with the target URL
            let matchingClient = null;
            let anyClient = null;

            for (let i = 0; i < windowClients.length; i++) {
                const client = windowClients[i];
                if (client.url === urlToOpen) {
                    matchingClient = client;
                    break;
                }
                if (!anyClient) anyClient = client; // Keep first available client as fallback
            }

            // If we have an exact match, focus it
            if (matchingClient) {
                return matchingClient.focus();
            }
            // If we have a window open but different URL, focus it and navigate
            else if (anyClient) {
                return anyClient.focus().then((c) => c.navigate(urlToOpen));
            }
            // Otherwise open a new window
            else {
                return clients.openWindow(urlToOpen);
            }
        })
    )
})
